
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu May 15 22:04:15 CEST 2025
//----------------------------------------------------

package constructorAst;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int EBOO = 50;
  public static final int POT = 42;
  public static final int WRTE = 55;
  public static final int CTE = 5;
  public static final int RET = 15;
  public static final int CAPE = 28;
  public static final int CASE = 12;
  public static final int CCIE = 29;
  public static final int TBOO = 52;
  public static final int LESS = 21;
  public static final int FOR = 8;
  public static final int EQLS = 13;
  public static final int ROBA = 37;
  public static final int AND = 44;
  public static final int NOT = 19;
  public static final int FLCH = 47;
  public static final int OR = 45;
  public static final int DIV = 41;
  public static final int GEQ = 23;
  public static final int EMPT = 56;
  public static final int SUMA = 38;
  public static final int MAIN = 53;
  public static final int IF = 6;
  public static final int OTWS = 14;
  public static final int GREA = 22;
  public static final int PAPE = 30;
  public static final int PTO = 35;
  public static final int EOF = 0;
  public static final int ASIG = 25;
  public static final int EINT = 49;
  public static final int error = 1;
  public static final int PCIE = 31;
  public static final int COMA = 34;
  public static final int MOD = 43;
  public static final int NEQ = 20;
  public static final int EQ = 18;
  public static final int DENO = 3;
  public static final int UNTL = 11;
  public static final int INTR = 36;
  public static final int TINT = 51;
  public static final int ELSE = 7;
  public static final int TUPL = 2;
  public static final int READ = 54;
  public static final int IDEN = 48;
  public static final int WHIL = 9;
  public static final int NMEM = 16;
  public static final int THEN = 46;
  public static final int DEL = 17;
  public static final int LEQ = 24;
  public static final int DOSP = 32;
  public static final int REPE = 10;
  public static final int LAPE = 26;
  public static final int PROD = 40;
  public static final int LCIE = 27;
  public static final int AS = 4;
  public static final int RSTA = 39;
  public static final int PYC = 33;
}

